name = "pokemon-precio-justo-sala"
main = "src/index.js"
compatibility_date = "2026-08-17"
workers_dev = true

[[durable_objects.bindings]]
name = "SALAS"
class_name = "SalaJuego"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SalaJuego"]
